apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: rgw-bucket-instance
  namespace: test-ns
spec:
  clusterServiceClassExternalName: rgw-bucket-service
  clusterServicePlanExternalName: default
  parameters:
    bucketName: "rgw-bucket-demo" # Optional
